# Form implementation generated from reading ui file 'D:\Spydecat_Doancuoiky\Spydecat_K24406H\ui\LoginMainWindowCanbo.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_can_bo_dang_nhap(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 638)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/ic_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 70, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(140, 100, 70);\n"
"font: 63 32pt\"Sitka Small Semibold\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEmail.setGeometry(QtCore.QRect(640, 150, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("background-color: rgb(200, 225, 245);\n"
"border:none;\n"
"border-bottom:3px solid rgb(33, 100, 207);\n"
"border-radius:12px;\n"
"font: 75 14pt \"Times New Roman\";")
        self.lineEditEmail.setText("")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(640, 230, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("background-color: rgb(200, 225, 245);\n"
"border:none;\n"
"border-bottom:3px solid rgb(33, 100, 207);\n"
"border-radius:12px;\n"
"font: 75 14pt \"Times New Roman\";")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(760, 520, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("background-color: rgb(200, 170, 130);\n"
"font: 14pt \"Times New Roman\";\n"
"border-radius:12px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/ic_loginn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon1)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(960, 520, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("background-color: rgb(200, 170, 130);\n"
"font: 14pt \"Times New Roman\";\n"
"border-radius:12px;")
        self.pushButtonExit.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Hausa, QtCore.QLocale.Country.Nigeria))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/ic_exitt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon2)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.lineEditCaptcha = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditCaptcha.setGeometry(QtCore.QRect(770, 310, 291, 51))
        self.lineEditCaptcha.setStyleSheet("font: 14pt \"Segoe Script\";\n"
"border-radius:12px;\n"
"background-color: rgb(200, 170, 130);")
        self.lineEditCaptcha.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditCaptcha.setObjectName("lineEditCaptcha")
        self.lineEditEnterCaptcha = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEnterCaptcha.setGeometry(QtCore.QRect(640, 440, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEditEnterCaptcha.setFont(font)
        self.lineEditEnterCaptcha.setStyleSheet("background-color: rgb(200, 225, 245);\n"
"border:none;\n"
"border-bottom:3px solid rgb(33, 100, 207);\n"
"border-radius:12px;\n"
"font: 75 14pt \"Times New Roman\";")
        self.lineEditEnterCaptcha.setObjectName("lineEditEnterCaptcha")
        self.pushButtonCaptcha = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCaptcha.setGeometry(QtCore.QRect(860, 380, 121, 41))
        self.pushButtonCaptcha.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgb(200, 170, 130);\n"
"border-radius:12px;\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/ic_captcha.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCaptcha.setIcon(icon3)
        self.pushButtonCaptcha.setObjectName("pushButtonCaptcha")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 601, 601))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/anhcanbo.jpg"))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1202, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cán bộ đăng nhập"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Đăng nhập</span></p></body></html>"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "Nhập Email"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.lineEditCaptcha.setText(_translate("MainWindow", "6qM5y3"))
        self.lineEditCaptcha.setPlaceholderText(_translate("MainWindow", "Mã captcha"))
        self.lineEditEnterCaptcha.setPlaceholderText(_translate("MainWindow", "Nhập dãy số trên"))
        self.pushButtonCaptcha.setText(_translate("MainWindow", "Captcha"))
