# Form implementation generated from reading ui file 'D:\Spydecat_Doancuoiky\Spydecat_K24406H\ui\MainWindowLuachondoituong.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_lua_chon(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/ic_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url('D:/Spydecat_Doancuoiky/Spydecat_K24406H/images/anhkhac.jpg');\n"
"background-repeat:none;\n"
"font: 8pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonKhach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonKhach.setGeometry(QtCore.QRect(400, 200, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonKhach.setFont(font)
        self.pushButtonKhach.setStyleSheet("#pushButtonKhach{\n"
"background:none;\n"
"background-color: rgb(255, 255, 255);\n"
"background-repeat:none;\n"
"font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 12px;}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/ic_khach.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonKhach.setIcon(icon1)
        self.pushButtonKhach.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonKhach.setObjectName("pushButtonKhach")
        self.pushButtonCanbo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCanbo.setGeometry(QtCore.QRect(400, 280, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonCanbo.setFont(font)
        self.pushButtonCanbo.setStyleSheet("#pushButtonCanbo{\n"
"background:none;\n"
"background-color: rgb(255, 255, 255);\n"
"background-repeat:none;\n"
"font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 12px;}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\Spydecat_Doancuoiky\\Spydecat_K24406H\\ui\\../images/ic_canbo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCanbo.setIcon(icon2)
        self.pushButtonCanbo.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonCanbo.setObjectName("pushButtonCanbo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lựa chọn đối tượng"))
        self.pushButtonKhach.setText(_translate("MainWindow", "Khách"))
        self.pushButtonCanbo.setText(_translate("MainWindow", "Cán bộ nhân viên"))
